---
name: Update dependencies

on:
  schedule:
    - cron: 34 3 * * 1

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get install -y libsndfile-dev ffmpeg
          make install

      - name: Disable pre-commit
        run: pre-commit uninstall

      - name: Update dependencies
        run: make update

      - name: Run tests
        run: make test

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt requirements-dev.txt docs/requirements.txt
          git diff-index --quiet HEAD \
            || git commit -m "build: update python dependencies"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
